import {writable} from 'svelte/store'

export var FoodData = writable([
  {
    name: "Tagliere della Casa",
    description: "Salumi e formaggi a Km 0, taralli di produzione propria, miele biologico.",
    cost: 12,
    group: "Antipasti",
    isGlutenfree: false,
    isFrozen: false,
    isVegetarian: false,
    isMilkfree: false,
    img: "tagliere-casa.jpg",
    engName: "House Charcuterie Board",
    engDescription: "Km 0 cured meats and cheeses, homemade taralli, organic honey."
  },
  {
    name: "Polpettine speziate con granella di arachidi",
    description: "Polpettine fritte di zucchine, curry, paprika, con panatura di granella di arachidi tostate.",
    cost: 6,
    group: "Antipasti",
    isGlutenfree: false,
    isFrozen: false,
    isVegetarian: true,
    isMilkfree: false,
    img: "polpettine-speziate.jpg",
    engName: "Spicy Peanut Meatballs",
    engDescription: "Fried zucchini meatballs with curry, paprika, and breadcrumb coating with toasted peanuts."
  },
  {
    name: "Involtini di Bresaola e Burrata",
    description: "Bresaola della Valtellina IGP punta d'anca, farcita con Burrata di Andria IGP ed erba cipollina.",
    cost: 8,
    group: "Antipasti",
    isGlutenfree: true,
    isFrozen: false,
    isVegetarian: false,
    isMilkfree: false,
    img: "involtini-bresaola.jpg",
    engName: "Bresaola and Burrata Rolls",
    engDescription: "Valtellina IGP beef bresaola, stuffed with Andria IGP burrata and chives."
  },
  {
    name: "Spaghetti allo scoglio",
    description: "Pasta di Gragnano IGP, con cozze, vongole, gamberi e calamari.",
    cost: 14,
    group: "Primi",
    isGlutenfree: false,
    isFrozen: true,
    isVegetarian: false,
    isMilkfree: true,
    img: "spaghetto-scoglio.jpg",
    engName: "Seafood Spaghetti",
    engDescription: "Gragnano IGP pasta with mussels, clams, shrimp, and squid."
  },
  {
    name: "Lasagnetta vegetariana con granella di mandorle",
    description: "Sfoglia di pasta acqua e farina, ragù vegetariano di melanzane e pomodoro San Marzano DOP, basilico e granella di mandorle.",
    cost: 9,
    group: "Primi",
    isGlutenfree: false,
    isFrozen: false,
    isVegetarian: true,
    isMilkfree: true,
    img: "lasagnetta-veg.jpg",
    engName: "Vegetarian Lasagnetta with Almond Crumble",
    engDescription: "Water and flour pasta sheet, vegetarian eggplant and San Marzano DOP tomato sauce, basil, and almond crumble."
  },
  {
    name: "Fettuccine al Ragù di Cervo",
    description: "Pasta all'uovo fatta in casa, Ragù di Cervo e formaggio Piave DOP.",
    cost: "12,5",
    group: "Primi",
    isGlutenfree: false,
    isFrozen: false,
    isVegetarian: false,
    isMilkfree: false,
    img: "fettuccine-ragu.jpg",
    engName: "Fettuccine with Venison Ragu",
    engDescription: "Homemade egg pasta with venison ragu and Piave DOP cheese."
  },
  {
    name: "Grigliata mista di Carne",
    description: "Carne a Km 0 (pollo, manzo, agnello), cotta su spiedo. Accompagnata da verdure biologiche di stagione e salse fatte in casa.",
    cost: 20,
    group: "Secondi",
    isGlutenfree: true,
    isFrozen: false,
    isVegetarian: false,
    isMilkfree: true,
    img: "grigliata-mista-carne.jpg",
    engName: "Mixed Meat Grill",
    engDescription: "Km 0 meats (chicken, beef, lamb) grilled on a spit. Served with seasonal organic vegetables and homemade sauces."
  },
  {
    name: "Grigliata mista di Mare",
    description: "Pescato del giorno, molluschi e crostacei cotti alla griglia.",
    cost: 22,
    group: "Secondi",
    isGlutenfree: true,
    isFrozen: true,
    isVegetarian: false,
    isMilkfree: true,
    img: "grigliata-mista-mare.jpg",
    engName: "Mixed Seafood Grill",
    engDescription: "Daily caught fish, mollusks, and crustaceans grilled."
  },
  {
    name: "Fungo Portobello ripieno",
    description: "Fungo Portobello cotto su griglia, ripieno di verdure di stagione e pesto fatto in casa. Servito con salsa di senape.",
    cost: 10,
    group: "Secondi",
    isGlutenfree: true,
    isFrozen: false,
    isVegetarian: true,
    isMilkfree: false,
    img: "fungo-portobello.jpg",
    engName: "Stuffed Portobello Mushroom",
    engDescription: "Portobello mushroom grilled and stuffed with seasonal vegetables and homemade pesto. Served with mustard sauce."
  },
  {
    name: "Tiramisù al bicchiere",
    description: "Savoiardi al caffè di nostra produzione, crema al mascarpone, spolverizzato con cacao amaro e cannella in polvere.",
    cost: 7,
    group: "Dessert",
    isGlutenfree: false,
    isFrozen: false,
    isVegetarian: false,
    isMilkfree: false,
    img: "tiramisu-bicchiere.jpg",
    engName: "Tiramisù in a Glass",
    engDescription: "Homemade coffee Savoiardi, mascarpone cream, dusted with bitter cocoa and cinnamon powder."
  },
  {
    name: "Semifreddo al Cocco",
    description: "Mousse al cocco, composta di passion fruit e foglie di menta.",
    cost: 7,
    group: "Dessert",
    isGlutenfree: true,
    isFrozen: false,
    isVegetarian: false,
    isMilkfree: false,
    img: "semifreddo-cocco.jpg",
    engName: "Coconut Semifreddo",
    engDescription: "Coconut mousse, passion fruit compote, and mint leaves."
  }
]);

export var DrinkData = writable([
  {
    name: "Barolo docg Cascina Chicco",
    description: "Uve: 100% Nebbiolo",
    size: "750ml",
    cost: 10,
    altSize: "",
    altCost: "",
    group: "Vino rosso",
    engName: "Barolo docg Cascina Chicco",
    engDescription: "Grape variety: 100% Nebbiolo",
    engAltSize: ""
  },
  {
    name: "Amarone Valpolicella docg Azienda Santi",
    description: "Uve: 70% Corvina, 20% Rondinella, 5% Oseleta, 5% Croatina",
    size: "750ml",
    cost: 10,
    altSize: "Calice",
    altCost: 3,
    group: "Vino rosso",
    engName: "Amarone Valpolicella docg Azienda Santi",
    engDescription: "Grape variety: 70% Corvina, 20% Rondinella, 5% Oseleta, 5% Croatina",
    engAltSize: "Glass"
  },
  {
    name: "Montepulciano d’Abruzzo Barone di Valforte",
    description: "Uve: 100% Montepulciano d’Abruzzo",
    size: "750ml",
    cost: 5,
    altSize: "",
    altCost: "",
    group: "Vino rosso",
    engName: "Montepulciano d’Abruzzo Barone di Valforte",
    engDescription: "Grape variety: 100% Montepulciano d’Abruzzo",
    engAltSize: ""
  },
  {
    name: "Gewurztraminer di Novacella",
    description: "Uve: 100% Gewurztraminer",
    size: "750ml",
    cost: 10,
    altSize: "",
    altCost: "",
    group: "Vino bianco",
    engName: "Gewurztraminer di Novacella",
    engDescription: "Grape variety: 100% Gewurztraminer",
    engAltSize: ""
  },
  {
    name: "Chardonnay Falesia 13%vol Az.d’Amico",
    description: "Uve: 100% Chardonnay",
    size: "750ml",
    cost: 21,
    altSize: "Calice",
    altCost: 8,
    group: "Vino bianco",
    engName: "Chardonnay Falesia 13%vol Az.d’Amico",
    engDescription: "Grape variety: 100% Chardonnay",
    engAltSize: "Glass"
  },
  {
    name: "Capolemole Igt Bio Marco Carpineti",
    description: "Uve: 100% Bellone",
    size: "750ml",
    cost: 22,
    altSize: "",
    altCost: "",
    group: "Vino bianco",
    engName: "Capolemole Igt Bio Marco Carpineti",
    engDescription: "Grape variety: 100% Bellone",
    engAltSize: ""
  },
  {
    name: "Itala Pilsen alla spina",
    description: "4,8 % Vol. Pils, biondo dorato, gusto ricco e distintivo",
    size: "200ml",
    cost: "3,5",
    altSize: "",
    altCost: "",
    group: "Birra",
    engName: "Itala Pilsen on tap",
    engDescription: "4.8% vol Blonde Pils, rich and distinctive taste",
    engAltSize: ""
  },
  {
    name: "Grolsch",
    description: "5,1 % Vol. Weizern, giallo paglierino, gusto rinfrescante e fruttato",
    size: "200ml",
    cost: "3,5",
    altSize: "",
    altCost: "",
    group: "Birra",
    engName: "Grolsch",
    engDescription: "Wheat beer, pale yellow, refreshing and fruity taste",
    engAltSize: ""
  },
  {
    name: "Acqua Naturale",
    description: "Mangiatorella",
    size: "1l",
    cost: 2,
    altSize: "0,5l",
    altCost: 1,
    group: "Analcolici",
    engName: "Natural Water",
    engDescription: "Mangiatorella",
    engAltSize: "0,5l"
  },
  {
    name: "Acqua Effervescente",
    description: "Ferrarelle",
    size: "1l",
    cost: 2,
    altSize: "0,5l",
    altCost: 1,
    group: "Analcolici",
    engName: "Sparkling water",
    engDescription: "Ferrarelle",
    engAltSize: "0,5l"
  },
  {
    name: "Coca Cola",
    description: "in lattina",
    size: "330ml",
    cost: 2,
    altSize: "",
    altCost: "",
    group: "Analcolici",
    engName: "Coca Cola",
    engDescription: "in can",
    engAltSize: ""
  },
  {
    name: "Coca Cola",
    description: "alla spina",
    size: "400ml",
    cost: 3,
    altSize: "200ml",
    altCost: 2,
    group: "Analcolici",
    engName: "Coca Cola",
    engDescription: "on tap",
    engAltSize: "200ml"
  },
  {
    name: "Espresso",
    description: "",
    size: "",
    cost: 1,
    altSize: "",
    altCost: "",
    group: "Bar",
    engName: "Espresso",
    engDescription: "",
    engAltSize: ""
  },
  {
    name: "Cappuccino",
    description: "",
    size: "",
    cost: "1,5",
    altSize: "",
    altCost: "",
    group: "Bar",
    engName: "Cappuccino",
    engDescription: "",
    engAltSize: ""
  }
])